export const MOCK_TABLE_DATA = [
	{
		id: 1,
		email: 'mphillins0@ask.com',
		avatar: 'https://robohash.org/facereexcepturiaut.png?size=50x50&set=set1',
		job: 'Payment Adjustment Coordinator',
		company: 'Demizz',
		gender: 'Male',
		ip: '24.177.178.73',
	},
	{
		id: 2,
		email: 'ssillick1@livejournal.com',
		avatar: 'https://robohash.org/doloribusquasireiciendis.png?size=50x50&set=set1',
		job: 'Systems Administrator IV',
		company: 'Vinte',
		gender: 'Male',
		ip: '8.52.158.164',
	},
	{
		id: 3,
		email: 'dfateley2@flavors.me',
		avatar: 'https://robohash.org/enimvellaborum.png?size=50x50&set=set1',
		job: 'Business Systems Development Analyst',
		company: 'Cogidoo',
		gender: 'Male',
		ip: '16.217.178.19',
	},
	{
		id: 4,
		email: 'cglasspoole3@nymag.com',
		avatar: 'https://robohash.org/earumeaaccusantium.png?size=50x50&set=set1',
		job: 'Operator',
		company: 'Ainyx',
		gender: 'Female',
		ip: '248.165.234.132',
	},
	{
		id: 5,
		email: 'rmars4@opensource.org',
		avatar: 'https://robohash.org/errornamcorporis.png?size=50x50&set=set1',
		job: 'Design Engineer',
		company: 'Zoomzone',
		gender: 'Bigender',
		ip: '48.40.225.250',
	},
	{
		id: 6,
		email: 'cwardrop5@360.cn',
		avatar: 'https://robohash.org/commodidoloresenim.png?size=50x50&set=set1',
		job: 'Office Assistant I',
		company: 'Fliptune',
		gender: 'Male',
		ip: '224.54.185.71',
	},
	{
		id: 7,
		email: 'smcpike6@oracle.com',
		avatar: 'https://robohash.org/etvitaemagnam.png?size=50x50&set=set1',
		job: 'Research Assistant IV',
		company: 'Centizu',
		gender: 'Female',
		ip: '86.37.81.61',
	},
	{
		id: 8,
		email: 'lescalante7@nba.com',
		avatar: 'https://robohash.org/ipsamutvoluptatem.png?size=50x50&set=set1',
		job: 'Senior Sales Associate',
		company: 'Browsezoom',
		gender: 'Male',
		ip: '240.4.136.76',
	},
	{
		id: 9,
		email: 'ndutnell8@ehow.com',
		avatar: 'https://robohash.org/dolorummagniet.png?size=50x50&set=set1',
		job: 'Human Resources Assistant II',
		company: 'Zoonder',
		gender: 'Male',
		ip: '216.17.122.47',
	},
	{
		id: 10,
		email: 'reggerton9@g.co',
		avatar: 'https://robohash.org/iustonesciuntsed.png?size=50x50&set=set1',
		job: 'Social Worker',
		company: 'Voonyx',
		gender: 'Female',
		ip: '35.84.15.174',
	},
]
